profile: coverage.out

threshold:
    file: 70
    package: 75
    total: 95

exclude:
    paths:
        - cmd/main.go
        - internal/api/docs/
        - internal/tests/
        - tmp/

override:
    - path: .go$
      threshold: 0
