profile: coverage.out

threshold:
  file: 70
  package: 80
  total: 95

exclude:
  paths:
    - cmd/main.go
    - internal/api-docs/
    - internal/api_test/
    - internal/test_helper/
    - tmp/scripts/toJWT.go

override:
  - path: .go$
    threshold: 0