// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/PMWPaymentStatus/verify": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Verifies PMW payment status attestation",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "PMWPaymentStatus"
                ],
                "summary": "Verify PMW Payment Status",
                "parameters": [
                    {
                        "description": "Attestation Request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/attestationtypes.AttestationRequestPMWPaymentStatus"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/attestationtypes.FullAttestationResponsePMWPaymentStatus"
                        }
                    }
                }
            }
        },
        "/TeeAvailabilityCheck/verify": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Verifies TEE availability check attestation",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "TEEAvailabilityCheck"
                ],
                "summary": "Verify TEE Availability Check",
                "parameters": [
                    {
                        "description": "Attestation Request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/attestationtypes.AttestationRequestTeeAvailabilityCheck"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/attestationtypes.FullAttestationResponseTeeAvailabilityCheck"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "attestationtypes.AttestationRequestPMWPaymentStatus": {
            "type": "object",
            "required": [
                "attestationType",
                "requestBody",
                "sourceId"
            ],
            "properties": {
                "attestationType": {
                    "type": "string",
                    "example": "0x4a736f6e41706900000000000000000000000000000000000000000000000000"
                },
                "requestBody": {
                    "$ref": "#/definitions/attestationtypes.IPMWPaymentStatusRequestBody"
                },
                "sourceId": {
                    "type": "string",
                    "example": "0x4a736f6e41706900000000000000000000000000000000000000000000000000"
                }
            }
        },
        "attestationtypes.AttestationRequestTeeAvailabilityCheck": {
            "type": "object",
            "required": [
                "attestationType",
                "requestBody",
                "sourceId"
            ],
            "properties": {
                "attestationType": {
                    "type": "string",
                    "example": "0x546565417661696c6162696c697479436865636b000000000000000000000000"
                },
                "requestBody": {
                    "$ref": "#/definitions/attestationtypes.ITeeAvailabilityCheckRequestBody"
                },
                "sourceId": {
                    "type": "string",
                    "example": "0x7465650000000000000000000000000000000000000000000000000000000000"
                }
            }
        },
        "attestationtypes.FullAttestationResponsePMWPaymentStatus": {
            "type": "object",
            "properties": {
                "attestationStatus": {
                    "type": "string"
                },
                "response": {
                    "type": "object",
                    "properties": {
                        "attestationType": {
                            "type": "string"
                        },
                        "requestBody": {
                            "$ref": "#/definitions/attestationtypes.IPMWPaymentStatusRequestBody"
                        },
                        "responseBody": {
                            "$ref": "#/definitions/attestationtypes.IPMWPaymentStatusResponseBody"
                        },
                        "sourceId": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "attestationtypes.FullAttestationResponseTeeAvailabilityCheck": {
            "type": "object",
            "properties": {
                "attestationStatus": {
                    "type": "string"
                },
                "response": {
                    "type": "object",
                    "properties": {
                        "attestationType": {
                            "type": "string"
                        },
                        "requestBody": {
                            "$ref": "#/definitions/attestationtypes.ITeeAvailabilityCheckRequestBody"
                        },
                        "responseBody": {
                            "$ref": "#/definitions/attestationtypes.ITeeAvailabilityCheckResponseBody"
                        },
                        "sourceId": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "attestationtypes.IPMWPaymentStatusRequestBody": {
            "type": "object",
            "required": [
                "nonce",
                "subNonce",
                "walletId"
            ],
            "properties": {
                "nonce": {
                    "type": "integer"
                },
                "subNonce": {
                    "type": "integer"
                },
                "walletId": {
                    "type": "string"
                }
            }
        },
        "attestationtypes.IPMWPaymentStatusResponseBody": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "string"
                },
                "blockNumber": {
                    "type": "integer"
                },
                "blockTimestamp": {
                    "type": "integer"
                },
                "fee": {
                    "type": "string"
                },
                "paymentReference": {
                    "type": "string"
                },
                "receivedAmount": {
                    "type": "string"
                },
                "recipientAddress": {
                    "type": "string"
                },
                "revertReason": {
                    "type": "string"
                },
                "senderAddress": {
                    "type": "string"
                },
                "transactionFee": {
                    "type": "string"
                },
                "transactionId": {
                    "type": "string"
                },
                "transactionStatus": {
                    "type": "integer"
                }
            }
        },
        "attestationtypes.ITeeAvailabilityCheckRequestBody": {
            "type": "object",
            "required": [
                "challenge",
                "teeId",
                "url"
            ],
            "properties": {
                "challenge": {
                    "type": "string",
                    "example": "12345678901234567890"
                },
                "teeId": {
                    "type": "string",
                    "example": "0x000000000000000000000000000000000000dEaD"
                },
                "url": {
                    "type": "string",
                    "example": "https://supertee.proxy"
                }
            }
        },
        "attestationtypes.ITeeAvailabilityCheckResponseBody": {
            "type": "object",
            "properties": {
                "codeHash": {
                    "type": "string"
                },
                "initialTeeId": {
                    "type": "string"
                },
                "machineStatus": {
                    "type": "integer"
                },
                "platform": {
                    "type": "string"
                },
                "rewardEpochId": {
                    "type": "string"
                },
                "status": {
                    "type": "integer"
                },
                "teeTimestamp": {
                    "type": "integer"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "type": "apiKey",
            "name": "X-API-KEY",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Verifier API",
	Description:      "API for verifying FTDC attestations",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
