definitions:
  attestationtypes.AttestationRequestPMWPaymentStatus:
    properties:
      attestationType:
        example: 0x4a736f6e41706900000000000000000000000000000000000000000000000000
        type: string
      requestBody:
        $ref: '#/definitions/attestationtypes.IPMWPaymentStatusRequestBody'
      sourceId:
        example: 0x4a736f6e41706900000000000000000000000000000000000000000000000000
        type: string
    required:
    - attestationType
    - requestBody
    - sourceId
    type: object
  attestationtypes.AttestationRequestTeeAvailabilityCheck:
    properties:
      attestationType:
        example: 0x546565417661696c6162696c697479436865636b000000000000000000000000
        type: string
      requestBody:
        $ref: '#/definitions/attestationtypes.ITeeAvailabilityCheckRequestBody'
      sourceId:
        example: 0x7465650000000000000000000000000000000000000000000000000000000000
        type: string
    required:
    - attestationType
    - requestBody
    - sourceId
    type: object
  attestationtypes.FullAttestationResponsePMWPaymentStatus:
    properties:
      attestationStatus:
        type: string
      response:
        properties:
          attestationType:
            type: string
          requestBody:
            $ref: '#/definitions/attestationtypes.IPMWPaymentStatusRequestBody'
          responseBody:
            $ref: '#/definitions/attestationtypes.IPMWPaymentStatusResponseBody'
          sourceId:
            type: string
        type: object
    type: object
  attestationtypes.FullAttestationResponseTeeAvailabilityCheck:
    properties:
      attestationStatus:
        type: string
      response:
        properties:
          attestationType:
            type: string
          requestBody:
            $ref: '#/definitions/attestationtypes.ITeeAvailabilityCheckRequestBody'
          responseBody:
            $ref: '#/definitions/attestationtypes.ITeeAvailabilityCheckResponseBody'
          sourceId:
            type: string
        type: object
    type: object
  attestationtypes.IPMWPaymentStatusRequestBody:
    properties:
      nonce:
        type: integer
      subNonce:
        type: integer
      walletId:
        type: string
    required:
    - nonce
    - subNonce
    - walletId
    type: object
  attestationtypes.IPMWPaymentStatusResponseBody:
    properties:
      amount:
        type: string
      blockNumber:
        type: integer
      blockTimestamp:
        type: integer
      fee:
        type: string
      paymentReference:
        type: string
      receivedAmount:
        type: string
      recipientAddress:
        type: string
      revertReason:
        type: string
      senderAddress:
        type: string
      transactionFee:
        type: string
      transactionId:
        type: string
      transactionStatus:
        type: integer
    type: object
  attestationtypes.ITeeAvailabilityCheckRequestBody:
    properties:
      challenge:
        example: "12345678901234567890"
        type: string
      teeId:
        example: "0x000000000000000000000000000000000000dEaD"
        type: string
      url:
        example: https://supertee.proxy
        type: string
    required:
    - challenge
    - teeId
    - url
    type: object
  attestationtypes.ITeeAvailabilityCheckResponseBody:
    properties:
      codeHash:
        type: string
      initialTeeId:
        type: string
      machineStatus:
        type: integer
      platform:
        type: string
      rewardEpochId:
        type: string
      status:
        type: integer
      teeTimestamp:
        type: integer
    type: object
info:
  contact: {}
  description: API for verifying FTDC attestations
  title: Verifier API
  version: "1.0"
paths:
  /PMWPaymentStatus/verify:
    post:
      consumes:
      - application/json
      description: Verifies PMW payment status attestation
      parameters:
      - description: Attestation Request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/attestationtypes.AttestationRequestPMWPaymentStatus'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/attestationtypes.FullAttestationResponsePMWPaymentStatus'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - ApiKeyAuth: []
      summary: Verify PMW Payment Status
      tags:
      - PMWPaymentStatus
  /TeeAvailabilityCheck/verify:
    post:
      consumes:
      - application/json
      description: Verifies TEE availability check attestation
      parameters:
      - description: Attestation Request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/attestationtypes.AttestationRequestTeeAvailabilityCheck'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/attestationtypes.FullAttestationResponseTeeAvailabilityCheck'
      security:
      - ApiKeyAuth: []
      summary: Verify TEE Availability Check
      tags:
      - TEEAvailabilityCheck
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: X-API-KEY
    type: apiKey
swagger: "2.0"
